version: "3"
volumes:
  postgres:
services:
  postgres:
    environment:
    - POSTGRES_DB=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
    image: postgres:12
    ports:
    - 5432:5432
    volumes:
    - postgres:/var/lib/postgresql
  openldap:
    image: osixia/openldap:1.3.0
    ports:
    - 8389:389
  keycloak:
    image:  jboss/keycloak:10.0.2
    command: -b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled
    depends_on:
    - postgres
    - openldap
    environment:
    - KEYCLOAK_USER=keycloak
    - KEYCLOAK_PASSWORD=password
    - KEYCLOAK_LOGLEVEL=INFO
    - DB_VENDOR=POSTGRES
    - DB_ADDR=postgres
    - DB_PORT=5432
    - DB_USER=keycloak
    - DB_DATABASE=keycloak
    - DB_PASSWORD=password
    ports:
    - 8080:8080
    volumes:
    - ./custom-user-federation-example/build/libs:/opt/jboss/keycloak/providers/

