site_name: "Terraform Provider: Keycloak"
site_url: https://mrparkers.github.io/terraform-provider-keycloak/
repo_url: https://github.com/mrparkers/terraform-provider-keycloak
nav:
- Getting Started: index.md
- Resources:
  - keycloak_realm: resources/keycloak_realm.md
  - keycloak_user: resources/keycloak_user.md
  - keycloak_group: resources/keycloak_group.md
  - keycloak_group_memberships: resources/keycloak_group_memberships.md
  - keycloak_openid_client: resources/keycloak_openid_client.md
  - keycloak_openid_client_scope: resources/keycloak_openid_client_scope.md
  - keycloak_openid_client_default_scopes: resources/keycloak_openid_client_default_scopes.md
  - keycloak_openid_client_optional_scopes: resources/keycloak_openid_client_optional_scopes.md
  - keycloak_openid_user_attribute_protocol_mapper: resources/keycloak_openid_user_attribute_protocol_mapper.md
  - keycloak_openid_user_property_protocol_mapper: resources/keycloak_openid_user_property_protocol_mapper.md
  - keycloak_openid_group_membership_protocol_mapper: resources/keycloak_openid_group_membership_protocol_mapper.md
  - keycloak_openid_hardcoded_claim_protocol_mapper:  resources/keycloak_openid_hardcoded_claim_protocol_mapper.md
  - keycloak_openid_full_name_protocol_mapper:  resources/keycloak_openid_full_name_protocol_mapper.md
  - keycloak_openid_audience_protocol_mapper:  resources/keycloak_openid_audience_protocol_mapper.md
  - keycloak_saml_client: resources/keycloak_saml_client.md
  - keycloak_saml_user_attribute_protocol_mapper: resources/keycloak_saml_user_attribute_protocol_mapper.md
  - keycloak_saml_user_property_protocol_mapper: resources/keycloak_saml_user_property_protocol_mapper.md
  - keycloak_ldap_user_federation:  resources/keycloak_ldap_user_federation.md
  - keycloak_ldap_full_name_mapper:  resources/keycloak_ldap_full_name_mapper.md
  - keycloak_ldap_group_mapper:  resources/keycloak_ldap_group_mapper.md
  - keycloak_ldap_msad_user_account_control_mapper:  resources/keycloak_ldap_msad_user_account_control_mapper.md
  - keycloak_ldap_user_attribute_mapper:  resources/keycloak_ldap_user_attribute_mapper.md
  - keycloak_custom_user_federation:  resources/keycloak_custom_user_federation.md
theme: readthedocs
extra_css: [index.css]
