site_name: "Terraform Provider: Keycloak"
site_url: https://mrparkers.github.io/terraform-provider-keycloak/
repo_url: https://github.com/mrparkers/terraform-provider-keycloak
nav:
- Getting Started: index.md
- Data Sources:
  - keycloak_group: data_sources/keycloak_group.md
  - keycloak_openid_client: data_sources/keycloak_openid_client.md
  - keycloak_realm: data_sources/keycloak_realm.md
  - keycloak_realm_keys: data_sources/keycloak_realm_keys.md
  - keycloak_role: data_sources/keycloak_role.md
  - keycloak_saml_client_installation_provider: data_sources/keycloak_saml_client_installation_provider.md
- Resources:
  - keycloak_realm: resources/keycloak_realm.md
  - keycloak_realm_events: resources/keycloak_realm_events.md
  - keycloak_role: resources/keycloak_role.md
  - keycloak_user: resources/keycloak_user.md
  - keycloak_user_roles: resources/keycloak_user_roles.md
  - keycloak_group: resources/keycloak_group.md
  - keycloak_group_memberships: resources/keycloak_group_memberships.md
  - keycloak_group_roles: resources/keycloak_group_roles.md
  - keycloak_default_groups: resources/keycloak_default_groups.md
  - keycloak_openid_client: resources/keycloak_openid_client.md
  - keycloak_openid_client_scope: resources/keycloak_openid_client_scope.md
  - keycloak_openid_client_default_scopes: resources/keycloak_openid_client_default_scopes.md
  - keycloak_openid_client_optional_scopes: resources/keycloak_openid_client_optional_scopes.md
  - keycloak_openid_user_attribute_protocol_mapper: resources/keycloak_openid_user_attribute_protocol_mapper.md
  - keycloak_openid_user_property_protocol_mapper: resources/keycloak_openid_user_property_protocol_mapper.md
  - keycloak_openid_group_membership_protocol_mapper: resources/keycloak_openid_group_membership_protocol_mapper.md
  - keycloak_openid_hardcoded_claim_protocol_mapper: resources/keycloak_openid_hardcoded_claim_protocol_mapper.md
  - keycloak_openid_full_name_protocol_mapper: resources/keycloak_openid_full_name_protocol_mapper.md
  - keycloak_openid_audience_protocol_mapper: resources/keycloak_openid_audience_protocol_mapper.md
  - keycloak_openid_hardcoded_role_protocol_mapper: resources/keycloak_openid_hardcoded_role_protocol_mapper.md
  - keycloak_openid_user_realm_role_protocol_mapper: resources/keycloak_openid_user_realm_role_protocol_mapper.md
  - keycloak_openid_user_client_role_protocol_mapper: resources/keycloak_openid_user_client_role_protocol_mapper.md
  - keycloak_openid_user_session_note_protocol_mapper: resources/keycloak_openid_user_session_note_protocol_mapper.md
  - keycloak_openid_client_service_account_role: resources/keycloak_openid_client_service_account_role.md
  - keycloak_saml_client: resources/keycloak_saml_client.md
  - keycloak_saml_user_attribute_protocol_mapper: resources/keycloak_saml_user_attribute_protocol_mapper.md
  - keycloak_saml_user_property_protocol_mapper: resources/keycloak_saml_user_property_protocol_mapper.md
  - keycloak_generic_client_protocol_mapper: resources/keycloak_generic_client_protocol_mapper.md
  - keycloak_ldap_user_federation: resources/keycloak_ldap_user_federation.md
  - keycloak_ldap_full_name_mapper: resources/keycloak_ldap_full_name_mapper.md
  - keycloak_ldap_group_mapper: resources/keycloak_ldap_group_mapper.md
  - keycloak_ldap_hardcoded_role_mapper: resources/keycloak_ldap_hardcoded_role_mapper.md
  - keycloak_ldap_msad_user_account_control_mapper: resources/keycloak_ldap_msad_user_account_control_mapper.md
  - keycloak_ldap_msad_lds_user_account_control_mapper: resources/keycloak_ldap_msad_lds_user_account_control_mapper.md
  - keycloak_ldap_user_attribute_mapper: resources/keycloak_ldap_user_attribute_mapper.md
  - keycloak_custom_user_federation: resources/keycloak_custom_user_federation.md
  - keycloak_saml_identity_provider: resources/keycloak_saml_identity_provider.md
  - keycloak_oidc_identity_provider: resources/keycloak_oidc_identity_provider.md
  - keycloak_generic_client_role_mapper: resources/keycloak_generic_client_role_mapper.md
  - keycloak_attribute_importer_identity_provider_mapper: resources/keycloak_attribute_importer_identity_provider_mapper.md
  - keycloak_authentication_execution: resources/keycloak_authentication_execution.md
  - keycloak_authentication_execution_config: resources/keycloak_authentication_execution_config.md
theme: readthedocs
extra_css: [index.css]
