version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-client-credentials
      - test-password
  release:
    jobs:
      - test-client-credentials:
          filters:
            tags:
              only: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/ # https://github.com/sindresorhus/semver-regex/blob/master/index.js
      - build:
          requires:
            - test-client-credentials
          filters:
            tags:
              only: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/ # https://github.com/sindresorhus/semver-regex/blob/master/index.js
      - release:
          requires:
            - build
          filters:
            tags:
              only: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/ # https://github.com/sindresorhus/semver-regex/blob/master/index.js
jobs:
  test-template: &test-template
    docker:
      - image: circleci/golang:1.11.4
      - image: jboss/keycloak:4.8.3.Final
        environment:
          DB_VENDOR: H2
          KEYCLOAK_LOGLEVEL: DEBUG
          KEYCLOAK_USER: keycloak
          KEYCLOAK_PASSWORD: password
    working_directory: /go/src/github.com/mrparkers/terraform-provider-keycloak
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-cache
      - run: go mod download
      - save_cache:
          key: go-cache
          paths:
            - /go/pkg
      - run:
          command: |
            ./scripts/wait-for-local-keycloak.sh
            ./scripts/create-terraform-client.sh
            make testacc
  test-client-credentials:
    <<: *test-template
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: terraform
      KEYCLOAK_URL: http://localhost:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT_SECRET: 884e0f95-0f42-4a63-9b1f-94274655669e
  test-password:
    <<: *test-template
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: admin-cli
      KEYCLOAK_URL: http://localhost:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password
  release:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/mrparkers/terraform-provider-keycloak
    steps:
      - checkout
      - run:
          command: |
            ./scripts/build-release.sh
            go get github.com/tcnksm/ghr
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -replace ${CIRCLE_TAG} ./artifacts
