version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.4
    - image: jboss/keycloak:4.2.1.Final
      environment:
        DB_VENDOR: H2
        KEYCLOAK_LOGLEVEL: DEBUG
        KEYCLOAK_USER: keycloak
        KEYCLOAK_PASSWORD: password
        KEYCLOAK_REALM: master
    working_directory: /go/src/github.com/mrparkers/terraform-provider-keycloak
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: "terraform"
      KEYCLOAK_CLIENT_SECRET: "884e0f95-0f42-4a63-9b1f-94274655669e"
      KEYCLOAK_URL: "http://localhost:8080"
    steps:
    - checkout
    - restore_cache:
        keys:
        - go-cache
    - run: go mod download
    - save_cache:
        key: go-cache
        paths:
        - /go/pkg
    - run:
        command: |
          ./scripts/wait-for-local-keycloak.sh
          ./scripts/create-terraform-client.sh
          make testacc
