version: 2.1
workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              keycloak-version:
                - '10.0.1'
                - '10.0.0'
                - '9.0.3'
                - '9.0.2'
                - '9.0.0'
                - '8.0.2'
                - '8.0.1'
                - '8.0.0'
                - '7.0.1'
                - '7.0.0'
                - '6.0.1'
                - '6.0.0'
                - '5.0.0'
                - '4.8.3'
  release:
    jobs:
      - test:
          keycloak-version: '8.0.1'
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-rc.\d+)?/
            branches:
              ignore: /.*/
      - build-and-release:
          requires:
            - test

defaults:
  go_image: &go_image
    - image: circleci/golang:1.13.5

jobs:
  test:
    parameters:
      keycloak-version:
        type: string
    docker:
      - <<: *go_image
      - image: jboss/keycloak:<< parameters.keycloak-version >>
        command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
        environment:
          DB_VENDOR: H2
          KEYCLOAK_LOGLEVEL: DEBUG
          KEYCLOAK_USER: keycloak
          KEYCLOAK_PASSWORD: password

    working_directory: /go/src/github.com/mrparkers/terraform-provider-keycloak
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-cache-{{ checksum "go.sum" }}
      - run: go mod download
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir $TEST_RESULTS
      - save_cache:
          key: go-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          command: |
            ./scripts/wait-for-local-keycloak.sh
            ./scripts/create-terraform-client.sh
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make testacc | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: "terraform"
      KEYCLOAK_CLIENT_SECRET: "884e0f95-0f42-4a63-9b1f-94274655669e"
      KEYCLOAK_CLIENT_TIMEOUT: "5"
      KEYCLOAK_URL: "http://localhost:8080"
      KEYCLOAK_REALM: "master"
      KEYCLOAK_TEST_PASSWORD_GRANT: "true"
      KEYCLOAK_VERSION: "<< parameters.keycloak-version >>"
      TEST_RESULTS: /tmp/test-results


  build-and-release:
    docker:
      - <<: *go_image
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/mrparkers/terraform-provider-keycloak
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "27:1c:fb:ea:7d:89:93:bb:13:54:5b:3f:b7:cc:1b:09"
      - run: go mod download
      - run:
          command: |
            ./scripts/build-release.sh
            ./scripts/publish-release.sh

