version: 2.1
workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              keycloak-version:
                - '12.0.1'
                - '11.0.3'
                - '10.0.2'

defaults:
  go_image: &go_image
    - image: circleci/golang:1.15.5

jobs:
  test:
    parameters:
      keycloak-version:
        type: string
    docker:
      - <<: *go_image
      - image: jboss/keycloak:<< parameters.keycloak-version >>
        command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.upload_scripts=enabled", "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled", "-Dkeycloak.profile.feature.token_exchange=enabled"]
        environment:
          DB_VENDOR: H2
          KEYCLOAK_LOGLEVEL: INFO
          KEYCLOAK_USER: keycloak
          KEYCLOAK_PASSWORD: password

    working_directory: /go/src/github.com/mrparkers/terraform-provider-keycloak
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-cache-{{ checksum "go.sum" }}
      - run: go mod download
      - run:
          name: Install go-junit-report
          command: |
            go get github.com/jstemmer/go-junit-report
            mkdir $TEST_RESULTS
      - save_cache:
          key: go-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          name: Install Terraform
          command: |
            curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip terraform_${TF_VERSION}_linux_amd64.zip
            sudo mv terraform ${TF_ACC_TERRAFORM_PATH}
            which terraform
            terraform version
      - run:
          name: Run Tests
          command: |
            ./scripts/wait-for-local-keycloak.sh
            ./scripts/create-terraform-client.sh
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make testacc | tee ${TEST_RESULTS}/go-test.out
          no_output_timeout: 30m
      - store_test_results:
          path: /tmp/test-results
    environment:
      KEYCLOAK_CLIENT_ID: "terraform"
      KEYCLOAK_CLIENT_SECRET: "884e0f95-0f42-4a63-9b1f-94274655669e"
      KEYCLOAK_CLIENT_TIMEOUT: "5"
      KEYCLOAK_URL: "http://localhost:8080"
      KEYCLOAK_REALM: "master"
      KEYCLOAK_TEST_PASSWORD_GRANT: "true"
      KEYCLOAK_VERSION: "<< parameters.keycloak-version >>"
      TEST_RESULTS: /tmp/test-results
      CHECKPOINT_DISABLE: "1"
      TF_ACC_TERRAFORM_PATH: "/usr/local/bin/terraform"
      TF_VERSION: "0.13.5"
